"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')  # This line should come *after* BASE_DIR is defined


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Django Security
SECRET_KEY = os.getenv("SECRET_KEY", "insecure-default-key")
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# Hosts — fully env-driven for white-label deployments
ALLOWED_HOSTS = [
    'localhost',
    'testserver',
    '127.0.0.1',
] + [h.strip() for h in os.getenv('ALLOWED_HOSTS_EXTRA', '').split(',') if h.strip()]

CORS_ALLOW_ALL_ORIGINS = True

# Django-hosts
PARENT_HOST = os.getenv('PARENT_HOST', 'we-fund.com')
ROOT_HOSTCONF = 'backend.hosts'
DEFAULT_HOST = os.getenv('DEFAULT_HOST', 'admin')
ROOT_URLCONF = 'backend.urls'

AUTH_USER_MODEL = 'wefund.User'

# Example:
# FTP_STORAGE_LOCATION = 'ftp://wefund:yourpass@storage.bunnycdn.com/wefundcdn/'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_hosts',
    'rest_framework',
    'corsheaders',
    'api',
    'wefund',
    'django_celery_beat',
    'storages',
    "rest_framework_simplejwt.token_blacklist",
]


MIDDLEWARE = [
    'django_hosts.middleware.HostsRequestMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_hosts.middleware.HostsResponseMiddleware',
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "wefund"),
        "USER": os.getenv("DB_USER", "nexada"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 25))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False").lower() in ("true", "1", "yes")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Support <support@example.com>')

# Support Email Settings
INBOUND_EMAIL_WEBHOOK_SECRET = os.getenv('INBOUND_EMAIL_WEBHOOK_SECRET', '')
SUPPORT_EMAIL_REPLY_DOMAIN = os.getenv('SUPPORT_EMAIL_REPLY_DOMAIN', 'we-fund.com')

# GitHub API Settings
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
GITHUB_ORG = 'commzilla'

# Celery Settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = os.getenv("CELERY_ACCEPT_CONTENT", "json").split(",")
CELERY_TASK_SERIALIZER = os.getenv("CELERY_TASK_SERIALIZER", "json")

CELERY_TASK_DEFAULT_QUEUE = 'celery'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# === MT5 Manager JSON API Settings ===
MT5_SERVER_NAME = os.getenv('MT5_SERVER_NAME', 'My Platform')
MT5_API_URL = os.getenv("MT5_API_URL", "")
MT5_API_KEY = os.getenv("MT5_API_KEY", "")

MT5_AGENT_ACCOUNT = int(os.getenv("MT5_AGENT_ACCOUNT", 0))
MT5_GROUP_NAME = os.getenv("MT5_GROUP_NAME", "")
MT5_LEVERAGE = int(os.getenv("MT5_LEVERAGE", 100))
MT5_USER_COLOR = int(os.getenv("MT5_USER_COLOR", 4278190080))
MT5_TAX_RATE = float(os.getenv("MT5_TAX_RATE", 1.0))

RISE_COMPANY_PRIVATE_KEY = os.getenv("RISE_COMPANY_PRIVATE_KEY", "")
RISE_COMPANY_WALLET = os.getenv("RISE_COMPANY_WALLET", "")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-sonnet-4-20250514")

EXCHANGE_RATE_API_KEY = os.getenv("EXCHANGE_RATE_API_KEY")

# ==========================
# Zoho Books Integration
# ==========================
ZOHO_BOOKS_CLIENT_ID = os.getenv("ZOHO_BOOKS_CLIENT_ID", "")
ZOHO_BOOKS_CLIENT_SECRET = os.getenv("ZOHO_BOOKS_CLIENT_SECRET", "")
ZOHO_BOOKS_REFRESH_TOKEN = os.getenv("ZOHO_BOOKS_REFRESH_TOKEN", "")
ZOHO_BOOKS_ORGANIZATION_ID = os.getenv("ZOHO_BOOKS_ORGANIZATION_ID", "")

# ==========================
# Daily.co Video Integration
# ==========================
DAILY_API_KEY = os.getenv('DAILY_API_KEY', '')
DAILY_API_URL = os.getenv('DAILY_API_URL', 'https://api.daily.co/v1')

# Google Calendar Integration
GOOGLE_CALENDAR_CLIENT_ID = os.getenv('GOOGLE_CALENDAR_CLIENT_ID', '')
GOOGLE_CALENDAR_CLIENT_SECRET = os.getenv('GOOGLE_CALENDAR_CLIENT_SECRET', '')
GOOGLE_CALENDAR_REDIRECT_URI = os.getenv('GOOGLE_CALENDAR_REDIRECT_URI', 'https://api.we-fund.com/api/admin/meetings/google/callback/')

# WeMeet Public URL
MEET_URL = os.getenv('MEET_URL', 'https://meet.we-fund.com')

# ==========================
# Twilio / WhatsApp / Voice
# ==========================
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER", "")
TWILIO_WEBHOOK_BASE_URL = os.getenv("TWILIO_WEBHOOK_BASE_URL", "https://api.we-fund.com")
WHATSAPP_AI_MODEL = os.getenv("WHATSAPP_AI_MODEL", "gemini-2.5-flash")
VOICE_WS_BASE_URL = os.getenv("VOICE_WS_BASE_URL", "wss://api.we-fund.com")

# ==========================
# RunPod AI Configuration
# ==========================

RUNPOD_API_KEY = os.getenv("RUNPOD_API_KEY", "")

RUNPOD_ENDPOINT_ID = os.getenv(
    "RUNPOD_ENDPOINT_ID",
    ""  # Empty by default, validated at runtime if used
)

RUNPOD_TIMEOUT_SECONDS = int(
    os.getenv("RUNPOD_TIMEOUT_SECONDS", "600")
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),     # extend to 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),    # allow refresh up to 30 days
    'ROTATE_REFRESH_TOKENS': True,                   # issue new refresh token each time
    'BLACKLIST_AFTER_ROTATION': True,                # old refresh tokens become invalid
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_CACHE_URL"),  # use db 1 to separate from Celery
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

WC_API_URL = os.getenv('WC_API_URL')
WC_CONSUMER_KEY = os.getenv('WC_CONSUMER_KEY')
WC_CONSUMER_SECRET = os.getenv('WC_CONSUMER_SECRET')
WC_WEBHOOK_SECRET = os.getenv('WC_WEBHOOK_SECRET')

# WordPress Plugin Integration Settings
WORDPRESS_PLUGIN_API_KEY = os.getenv('WORDPRESS_PLUGIN_API_KEY', 'wp_plugin_test_key_secure_12345678901234567890')

DISCORD_PAYOUT_WEBHOOK_URL = os.getenv("DISCORD_PAYOUT_WEBHOOK_URL")
# Health alert Slack webhook — used by `manage.py health_alert` (cron job, not Celery).
# Setup: add SLACK_HEALTH_WEBHOOK_URL to .env, then set up cron. See CLAUDE.md for details.
SLACK_HEALTH_WEBHOOK_URL = os.getenv("SLACK_HEALTH_WEBHOOK_URL")

KLAVIYO_PRIVATE_API_KEY = os.getenv("KLAVIYO_PRIVATE_API_KEY", "")

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_PAYOUT_CHAT_ID = os.getenv("TELEGRAM_PAYOUT_CHAT_ID")

# Payment Gateway Settings
PAYTIKO_API_KEY = os.getenv('PAYTIKO_API_KEY')
PAYTIKO_API_URL = os.getenv('PAYTIKO_API_URL', 'https://api.paytiko.com/v1/payments')
CONFIRMO_API_KEY = os.getenv('CONFIRMO_API_KEY')
CONFIRMO_CALLBACK_PASSWORD = os.getenv('CONFIRMO_CALLBACK_PASSWORD')
CONFIRMO_API_URL = os.getenv('CONFIRMO_API_URL', 'https://confirmo.net/api/v3/invoices')
PAYPAL_CLIENT_ID = os.getenv('PAYPAL_CLIENT_ID')
PAYPAL_SECRET_KEY = os.getenv('PAYPAL_SECRET_KEY')
PAYPAL_API_URL = os.getenv('PAYPAL_API_URL', 'https://api-m.paypal.com')
PAYPAL_WEBHOOK_ID = os.getenv('PAYPAL_WEBHOOK_ID')

# Website URLs
WEBSITE_URL = os.getenv('WEBSITE_URL', 'https://www.we-fund.com')
API_BASE_URL = os.getenv('API_BASE_URL', 'https://api.we-fund.com/api')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING_DIR = BASE_DIR / 'logs'
LOGGING_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        '__main__': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'storages.backends.ftp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Default context processors...
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'

# # Optional but good practice:
# STATICFILES_DIRS = [
#     BASE_DIR / "static",  # Only if you have global static files
# ]

# # Required for collectstatic (useful even in dev)
# STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FRONTEND_URL = os.getenv("FRONTEND_URL")

# Media URL should point to your Pull Zone URL
MEDIA_URL = os.getenv("MEDIA_URL", "")  # Replace with your BunnyCDN Pull Zone URL

REGION = os.getenv("REGION", "")
BUNNYCDN_STORAGE_ZONE = os.getenv("BUNNYCDN_STORAGE_ZONE", "")
BUNNYCDN_API_KEY = os.getenv("BUNNYCDN_API_KEY", "")
BUNNYCDN_PULL_ZONE_URL = os.getenv("BUNNYCDN_PULL_ZONE_URL", "")

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
