// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdbwwgnioqhxxmifvjam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkYnd3Z25pb3FoeHhtaWZ2amFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMDM4MzQsImV4cCI6MjA3Nzg3OTgzNH0.mj-_dKvBFQ5fyGebRZBGtzRjl1L9IH5NrpbOR3XkDIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});