# Generated by Django 5.2.2 on 2025-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0002_clientprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('challenge_type', models.CharField(choices=[('one_step', '1-Step'), ('two_step', '2-Step')], max_length=20)),
                ('account_size', models.DecimalField(decimal_places=2, help_text='Account size in USD', max_digits=12)),
                ('entry_fee', models.DecimalField(decimal_places=2, help_text='Fee to join the challenge', max_digits=10)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_total_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_target_phase_1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profit_target_phase_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Optional challenge rules/config')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
