# Generated by Django 5.2.2 on 2025-06-09 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0003_challengeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('phase_1_in_progress', 'Phase 1 - In Progress'), ('phase_1_passed', 'Passed Phase 1'), ('phase_2_in_progress', 'Phase 2 - In Progress'), ('phase_2_passed', 'Passed Phase 2'), ('failed', 'Failed')], default='phase_1_in_progress', max_length=30)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wefund.challengeproduct')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_enrollments', to='wefund.clientprofile')),
            ],
            options={
                'unique_together': {('client', 'challenge')},
            },
        ),
    ]
