# Generated by Django 5.2.2 on 2025-06-11 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0005_clientkyc_delete_kycdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='current_fee_tier',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='kyc_documents',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='total_withdrawals',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address_info',
            field=models.JSONField(default=dict, help_text='\n        Store full address and contact details in this format:\n        {\n            "first_name": "",\n            "last_name": "",\n            "company": "",\n            "address_line_1": "",\n            "address_line_2": "",\n            "city": "",\n            "postcode": "",\n            "state": "",\n            "country": "",\n            "email": "",\n            "phone": ""\n        }\n        '),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partial', 'Partially Paid')], default='unpaid', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('billing_address', models.JSONField(default=dict, help_text='Full billing address (as JSON)')),
                ('product_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('items_subtotal_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('coupons_discount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order_total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('coupon_codes', models.JSONField(blank=True, default=list, help_text='List of applied coupon codes')),
                ('payment_method', models.CharField(max_length=100)),
                ('raw_data', models.JSONField(default=dict, help_text='Complete raw order payload from WooCommerce or external source')),
                ('user', models.ForeignKey(blank=True, help_text='User (if matched) in the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
