# Generated by Django 5.2.2 on 2025-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0006_remove_clientprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.JSONField(default=dict, help_text='\n        Store full billing address and contact details in this format:\n        {\n            "first_name": "",\n            "last_name": "",\n            "company": "",\n            "address_line_1": "",\n            "address_line_2": "",\n            "city": "",\n            "postcode": "",\n            "state": "",\n            "country": "",\n            "email": "",\n            "phone": ""\n        }\n        '),
        ),
    ]
