# Generated by Django 5.2.3 on 2025-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0007_alter_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mt5_account_id',
            field=models.CharField(blank=True, help_text='MT5 account login ID returned by MT5 API', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_investor_password',
            field=models.CharField(blank=True, help_text='MT5 investor (read-only) password generated', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_password',
            field=models.CharField(blank=True, help_text='MT5 master password generated (not hashed)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_payload_sent',
            field=models.JSONField(blank=True, default=dict, help_text='Payload sent to MT5 AddUser API'),
        ),
        migrations.AddField(
            model_name='order',
            name='mt5_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response received from MT5 AddUser API'),
        ),
        migrations.AddField(
            model_name='order',
            name='plaintext_password',
            field=models.CharField(blank=True, help_text='Plaintext login password for user account (not hashed, for email only)', max_length=50, null=True),
        ),
    ]
