# Generated by Django 5.2.3 on 2025-07-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0008_order_mt5_account_id_order_mt5_investor_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('step_type', models.CharField(choices=[('1-step', '1 Step'), ('2-step', '2 Step')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='challengeenrollment',
            name='account_size',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Account size selected (e.g. 50000.00)', max_digits=12),
        ),
        migrations.AddField(
            model_name='challengeenrollment',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency of the account', max_length=10),
        ),
        migrations.AlterField(
            model_name='challengeenrollment',
            name='status',
            field=models.CharField(choices=[('phase_1_in_progress', 'Phase 1 - In Progress'), ('phase_1_passed', 'Phase 1 - Passed'), ('phase_2_in_progress', 'Phase 2 - In Progress'), ('phase_2_passed', 'Phase 2 - Passed'), ('live_in_progress', 'Live - In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='phase_1_in_progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='challengeenrollment',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wefund.challenge'),
        ),
        migrations.CreateModel(
            name='ChallengePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('phase-1', 'Phase 1'), ('phase-2', 'Phase 2'), ('live-trader', 'Live Trader')], max_length=20)),
                ('trading_period', models.CharField(default='Unlimited', max_length=50)),
                ('min_trading_days', models.CharField(default='0', max_length=20)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_loss', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit_target', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if not applicable', max_digits=5, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='wefund.challenge')),
            ],
            options={
                'unique_together': {('challenge', 'phase_type')},
            },
        ),
    ]
