# Generated by Django 5.2.3 on 2025-07-13 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0010_offer_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('email', 'Letter at E-mail'), ('sms', 'SMS'), ('phone_call', 'Phone Call'), ('auth_app', 'Authenticator App')], help_text='Preferred method for receiving 2FA codes.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_new_challenge', models.BooleanField(default=True)),
                ('system_announcements', models.BooleanField(default=True)),
                ('system_risk_alerts', models.BooleanField(default=True)),
                ('system_community', models.BooleanField(default=True)),
                ('system_platform', models.BooleanField(default=True)),
                ('email_new_challenge', models.BooleanField(default=True)),
                ('email_announcements', models.BooleanField(default=True)),
                ('email_risk_alerts', models.BooleanField(default=True)),
                ('email_community', models.BooleanField(default=True)),
                ('email_platform', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
