# Generated by Django 5.2.3 on 2025-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0011_user_two_factor_method_notificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth (optional).", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture (optional).", null=True, upload_to='profiles/'),
        ),
    ]
