# Generated by Django 5.2.3 on 2025-07-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0012_user_date_of_birth_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='challenge_account_size',
            field=models.CharField(blank=True, help_text="Account size string, e.g., '10000' or '$10,000'", max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='challenge_broker_type',
            field=models.CharField(blank=True, help_text="Broker type from product metadata, e.g., 'mt5'", max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='challenge_name',
            field=models.CharField(blank=True, help_text='Parent product or challenge name', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='woo_customer_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='woo_order_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='woo_order_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='woo_order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
