# Generated by Django 5.2.3 on 2025-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0013_order_challenge_account_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeenrollment',
            name='broker_type',
            field=models.CharField(blank=True, help_text="Broker type, e.g., 'mt5', 'mt4'", max_length=10),
        ),
        migrations.AddField(
            model_name='challengeenrollment',
            name='mt5_account_id',
            field=models.CharField(blank=True, help_text='MT5 account login ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='challengeenrollment',
            name='mt5_investor_password',
            field=models.CharField(blank=True, help_text='MT5 investor (read-only) password', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='challengeenrollment',
            name='mt5_password',
            field=models.CharField(blank=True, help_text='MT5 master password (not hashed)', max_length=50, null=True),
        ),
    ]
