# Generated by Django 5.2.3 on 2025-07-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0014_challengeenrollment_broker_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeenrollment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefund.order'),
        ),
    ]
