# Generated by Django 5.2.3 on 2025-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0015_challengeenrollment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('order', models.BigIntegerField(unique=True)),
                ('timestamp', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('digits', models.IntegerField()),
                ('cmd', models.IntegerField()),
                ('volume', models.FloatField()),
                ('open_time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close_time', models.DateTimeField()),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sl', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tp', models.DecimalField(decimal_places=6, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_agent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_date', models.BigIntegerField(default=0)),
                ('expiration', models.BigIntegerField(default=0)),
                ('conv_reserv', models.BigIntegerField(default=0)),
                ('open_conv_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('close_conv_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('magic', models.BigIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('spread', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-close_time'],
                'indexes': [models.Index(fields=['account_id', 'order'], name='wefund_mt5t_account_f87558_idx'), models.Index(fields=['symbol'], name='wefund_mt5t_symbol_b695cc_idx'), models.Index(fields=['open_time'], name='wefund_mt5t_open_ti_40f3af_idx'), models.Index(fields=['close_time'], name='wefund_mt5t_close_t_273a85_idx')],
            },
        ),
    ]
