# Generated by Django 5.2.3 on 2025-07-13 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0016_mt5trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested payout amount (usually equal to net profit)', max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Total trading profit earned during the payout period', max_digits=12)),
                ('profit_share', models.DecimalField(decimal_places=2, default=80.0, help_text='Profit share percentage agreed for the trader (e.g., 80%)', max_digits=5)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Net amount due to trader after applying profit share', max_digits=12)),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Crypto')], help_text='Chosen payout method', max_length=20)),
                ('method_details', models.JSONField(blank=True, default=dict, help_text='Details for the selected payout method, e.g.:\n        {\n            "paypal_email": "",\n            "bank_account": "",\n            "crypto_wallet": "",\n            "bank_name": "",\n            ...\n        }')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payout request status', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Optional internal note from admin (e.g., rejection reason)', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('trader', models.ForeignKey(help_text='Client requesting payout', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trader Payout',
                'verbose_name_plural': 'Trader Payouts',
                'ordering': ['-requested_at'],
            },
        ),
    ]
