# Generated by Django 5.2.3 on 2025-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0017_traderpayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='feature_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
