# Generated by Django 5.2.3 on 2025-07-19 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0018_alter_offer_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('phase_pass', 'Challenge Phase Pass'), ('payout', 'Payout Certificate')], help_text='Type of certificate', max_length=30)),
                ('image_url', models.URLField(blank=True, help_text='Public CDN URL for certificate image', max_length=500, null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Public CDN URL for certificate PDF', max_length=500, null=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional info or data (e.g., certificate version)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, help_text='Link if certificate is tied to a challenge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='wefund.challengeenrollment')),
                ('payout', models.ForeignKey(blank=True, help_text='Link if certificate is tied to a payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='wefund.traderpayout')),
                ('user', models.ForeignKey(help_text='Client who owns this certificate', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
            },
        ),
    ]
