# Generated by Django 5.2.3 on 2025-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0019_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(default='Unknown', help_text='Custom title for the certificate (e.g., "Phase 1 Passed - $50K Challenge")', max_length=255),
            preserve_default=False,
        ),
    ]
