# Generated by Django 5.2.3 on 2025-07-19 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0020_certificate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Crypto Wallet')], help_text='Type of payment method (PayPal, Bank, Crypto)', max_length=20)),
                ('paypal_email', models.EmailField(blank=True, help_text='PayPal account email address', max_length=254, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_country', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('crypto_type', models.CharField(blank=True, choices=[('usdt_trc20', 'USDT - TRC20'), ('usdt_erc20', 'USDT - ERC20'), ('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('other', 'Other')], help_text='Type of crypto wallet (e.g., USDT TRC20)', max_length=20, null=True)),
                ('crypto_wallet_address', models.CharField(blank=True, help_text='Crypto wallet address', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default payment method?')),
                ('label', models.CharField(blank=True, help_text='Optional label like "My Binance Wallet" or "Main Bank Account"', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client to whom this payment method belongs', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Payment Method',
                'verbose_name_plural': 'Client Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
