# Generated by Django 5.2.3 on 2025-07-19 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0021_clientpaymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_trading_start_date', models.DateField(help_text='Date when client started trading on live account')),
                ('profit_share_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage of profit that the trader receives (e.g., 80 means 80% to trader)', max_digits=5)),
                ('payment_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly')], default='monthly', help_text='How often the client can request a payout', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or admin remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
