# Generated by Django 5.2.3 on 2025-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0022_payoutconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="Publicly accessible URL of the user's profile picture (e.g. from BunnyCDN).", max_length=500, null=True),
        ),
    ]
