# Generated by Django 5.2.3 on 2025-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0023_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeenrollment',
            name='live_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
