# Generated by Django 5.2.3 on 2025-07-23 10:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0024_challengeenrollment_live_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliateprofile',
            name='commission_earned',
        ),
        migrations.RemoveField(
            model_name='affiliateprofile',
            name='commission_paid',
        ),
        migrations.RemoveField(
            model_name='affiliateprofile',
            name='commission_pending',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='challenge_completed',
        ),
        migrations.RemoveField(
            model_name='affiliatereferral',
            name='payout_status',
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 10, 2, 58, 400158, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='promotion_strategy',
            field=models.TextField(blank=True, help_text='How the affiliate plans to promote We-Fund (socials, email, paid ads, etc.)'),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text="Affiliate's website or landing page (optional).", max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='affiliatereferral',
            name='challenge_name',
            field=models.CharField(blank=True, help_text='Name of the challenge the referred user joined (optional).', max_length=100),
        ),
        migrations.AddField(
            model_name='affiliatereferral',
            name='commission_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status of the commission.', max_length=20),
        ),
        migrations.AddField(
            model_name='affiliatereferral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='affiliatereferral',
            name='note',
            field=models.TextField(blank=True, help_text='Optional internal notes about this referral.'),
        ),
        migrations.AddField(
            model_name='affiliatereferral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliateprofile',
            name='referral_code',
            field=models.CharField(db_index=True, help_text='A unique code/slug that affiliates share with clients.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='affiliatereferral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
