# Generated by Django 5.2.3 on 2025-07-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0025_remove_affiliateprofile_commission_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
    ]
