# Generated by Django 5.2.3 on 2025-07-24 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0029_affiliateclick'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeenrollment',
            unique_together=set(),
        ),
    ]
