# Generated by Django 5.2.3 on 2025-07-30 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0030_alter_challengeenrollment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested or paid (in USD or your system currency)', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payout request', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin or system notes about this payout (e.g., reason for rejection)', null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the affiliate requested the payout')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout was approved or marked as paid', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID (e.g., from PayPal, bank, crypto)', max_length=100, null=True)),
                ('is_manual', models.BooleanField(default=False, help_text='Whether this payout was manually created by admin (outside of a user request)')),
                ('affiliate', models.ForeignKey(help_text='The affiliate user requesting or receiving the payout', limit_choices_to={'role': 'affiliate'}, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_payouts', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, help_text='The payment method to use for this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefund.clientpaymentmethod')),
            ],
            options={
                'verbose_name': 'Affiliate Payout',
                'verbose_name_plural': 'Affiliate Payouts',
                'ordering': ['-requested_at'],
            },
        ),
    ]
