# Generated by Django 5.2.3 on 2025-07-30 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0031_affiliatepayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance (available for payout)', max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commissions earned to date (lifetime)', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('affiliate', models.OneToOneField(help_text='The affiliate who owns this wallet', limit_choices_to={'role': 'affiliate'}, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('commission', 'Commission Earned'), ('bonus', 'Bonus'), ('adjustment', 'Manual Adjustment'), ('payout', 'Payout Deducted'), ('reversal', 'Reversed/Refunded')], help_text='Type of transaction', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credit, negative for debit', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='approved', help_text='Transaction status (pending, approved, rejected, etc.)', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Additional context or description for this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_payout', models.ForeignKey(blank=True, help_text='Optional: Linked payout if this is a deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefund.affiliatepayout')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wefund.affiliatewallet')),
            ],
            options={
                'verbose_name': 'Affiliate Wallet Transaction',
                'verbose_name_plural': 'Affiliate Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, help_text='The wallet transaction that debited this payout amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_reference', to='wefund.affiliatewallettransaction'),
        ),
    ]
