# Generated by Django 5.2.3 on 2025-07-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0032_affiliatewallet_affiliatewallettransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='challenge_enrollment',
            field=models.ForeignKey(blank=True, help_text='The challenge enrollment (account) this payout is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='wefund.challengeenrollment'),
        ),
    ]
