# Generated by Django 5.2.3 on 2025-08-07 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0033_traderpayout_challenge_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('breached_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_records', to='wefund.clientprofile')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_records', to='wefund.challengeenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-breached_at'],
            },
        ),
    ]
