# Generated by Django 5.2.3 on 2025-08-07 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0034_breachhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user'], name='wefund_logi_user_id_91acb9_idx'), models.Index(fields=['ip_address'], name='wefund_logi_ip_addr_358239_idx'), models.Index(fields=['device_fingerprint'], name='wefund_logi_device__5feb89_idx'), models.Index(fields=['login_time'], name='wefund_logi_login_t_ab5a4c_idx')],
            },
        ),
    ]
