# Generated by Django 5.2.3 on 2025-08-14 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0035_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_type', models.CharField(choices=[('phase-1', 'Phase 1'), ('phase-2', 'Phase 2'), ('live-trader', 'Live Trader')], max_length=20)),
                ('broker_type', models.CharField(default='mt5', max_length=10)),
                ('mt5_account_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mt5_password', models.CharField(blank=True, max_length=100, null=True)),
                ('mt5_investor_password', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wefund.challengeenrollment')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'phase_type', 'status'], name='wefund_enro_enrollm_f4c6f6_idx'), models.Index(fields=['mt5_account_id'], name='wefund_enro_mt5_acc_9caefa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('enrollment', 'phase_type', 'status'), name='uniq_active_account_per_phase')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentTransitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='wefund.challengeenrollment')),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'created_at'], name='wefund_enro_enrollm_053202_idx')],
            },
        ),
    ]
