# Generated by Django 5.2.3 on 2025-08-14 05:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0036_enrollmentaccount_enrollmenttransitionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftBreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField()),
                ('rule', models.CharField(max_length=100)),
                ('severity', models.CharField(default='low', max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soft_breaches', to='wefund.clientprofile')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soft_breaches', to='wefund.challengeenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_breaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Soft Breach',
                'verbose_name_plural': 'Soft Breaches',
                'ordering': ['-detected_at'],
            },
        ),
    ]
