# Generated by Django 5.2.3 on 2025-08-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0037_softbreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='softbreach',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soft_breaches', to='wefund.traderpayout'),
        ),
    ]
