# Generated by Django 5.2.3 on 2025-08-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0038_softbreach_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_custom',
            field=models.BooleanField(blank=True, help_text='True if this is a custom notification for a single user', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_global',
            field=models.BooleanField(blank=True, help_text='Marks this notification as global', null=True),
        ),
    ]
