# Generated by Django 5.2.3 on 2025-08-15 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0039_notification_is_custom_notification_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderPayoutAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_recommendations', models.TextField(blank=True, help_text='AI recommendations to improve trading')),
                ('ai_trading_review', models.TextField(blank=True, help_text='Full AI trading review summary')),
                ('summary', models.TextField(blank=True, help_text='Summary of the AI analysis')),
                ('trading_style', models.CharField(blank=True, help_text='Identified trading style (e.g., Conservative, Aggressive)', max_length=100)),
                ('risk_assessment', models.CharField(blank=True, help_text='Risk assessment determined by AI (Low, Medium, High)', max_length=100)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Risk score (0-100) calculated by AI', max_digits=5, null=True)),
                ('recommendation', models.TextField(blank=True, help_text='AI recommendation regarding payout approval or trading improvement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.OneToOneField(help_text='The payout this AI analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='wefund.traderpayout')),
            ],
            options={
                'verbose_name': 'Trader Payout AI Analysis',
                'verbose_name_plural': 'Trader Payout AI Analyses',
            },
        ),
    ]
