# Generated by Django 5.2.3 on 2025-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0040_traderpayoutaianalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='risk_assessment',
            field=models.TextField(blank=True, help_text='Risk assessment determined by AI (Low, Medium, High)'),
        ),
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='trading_style',
            field=models.TextField(blank=True, help_text='Identified trading style (e.g., Conservative, Aggressive)'),
        ),
    ]
