# Generated by Django 5.2.3 on 2025-08-20 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0041_alter_traderpayoutaianalysis_risk_assessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EATradingBotRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mq5_file_url', models.URLField(help_text='BunnyCDN / S3 URL to the uploaded .mq5 file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current approval status of the EA request', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text="Reason for rejection if status is 'rejected'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client requesting EA approval', on_delete=django.db.models.deletion.CASCADE, related_name='ea_requests', to='wefund.clientprofile')),
                ('enrollment', models.ForeignKey(help_text='The specific challenge enrollment this EA request is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='ea_requests', to='wefund.challengeenrollment')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/staff who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ea_reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
