# Generated by Django 5.2.3 on 2025-08-20 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0042_eatradingbotrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCommissionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Tier name (e.g. 'Tier 1')", max_length=100)),
                ('min_referrals', models.PositiveIntegerField(help_text='Minimum number of referrals required to qualify for this tier')),
                ('max_referrals', models.PositiveIntegerField(blank=True, help_text='Maximum number of referrals for this tier. Leave blank for unlimited.', null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage for this tier (e.g. 10.00 for 10%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_referrals'],
            },
        ),
    ]
