# Generated by Django 5.2.3 on 2025-08-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0043_affiliatecommissiontier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='AffiliateProfile that referred this user/order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wefund.affiliateprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Affiliate referral code used for this order, if any', max_length=32, null=True),
        ),
    ]
