# Generated by Django 5.2.3 on 2025-08-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0044_order_affiliate_order_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, if status is rejected', null=True),
        ),
    ]
