# Generated by Django 5.2.3 on 2025-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0045_traderpayout_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='AI recommendations to improve trading'),
        ),
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='recommendation',
            field=models.JSONField(blank=True, default=dict, help_text='AI recommendation regarding payout approval or trading improvement'),
        ),
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='risk_assessment',
            field=models.JSONField(blank=True, default=dict, help_text='Risk assessment determined by AI'),
        ),
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of the AI analysis'),
        ),
        migrations.AlterField(
            model_name='traderpayoutaianalysis',
            name='trading_style',
            field=models.JSONField(blank=True, default=dict, help_text='Identified trading style (e.g., Conservative, Aggressive)'),
        ),
    ]
