# Generated by Django 5.2.3 on 2025-08-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0046_alter_traderpayoutaianalysis_ai_recommendations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('breach', 'Breach'), ('phase_pass', 'Phase Passed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional: reason or rule triggered')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wefund.challengeenrollment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
