# Generated by Django 5.2.3 on 2025-08-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0047_enrollmentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengePhaseGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_group', models.CharField(help_text="MT5 group name as in MT5 'groups' table (e.g. demo\\WEF\\Group-1)", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('challenge_phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_mapping', to='wefund.challengephase')),
            ],
            options={
                'verbose_name': 'Challenge Phase Group Mapping',
                'verbose_name_plural': 'Challenge Phase Group Mappings',
            },
        ),
    ]
