# Generated by Django 5.2.3 on 2025-08-28 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0048_challengephasegroupmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the CSV was uploaded')),
                ('file_name', models.CharField(help_text='Original name of the uploaded CSV file', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total number of rows in the uploaded CSV')),
                ('created_rows', models.PositiveIntegerField(default=0, help_text='Number of successfully created records')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of errors encountered during import, if any')),
                ('notes', models.TextField(blank=True, help_text='Optional notes or comments about the migration', null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Admin user who performed the migration', limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Migration History',
                'verbose_name_plural': 'Migration Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
