# Generated by Django 5.2.3 on 2025-09-01 08:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0049_migrationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderPayoutComplianceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('hard_breach_detected', models.BooleanField(default=False)),
                ('soft_breach_detected', models.BooleanField(default=False)),
                ('hard_breaches', models.JSONField(blank=True, default=list)),
                ('soft_breaches', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('payout_adjustments', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout', models.OneToOneField(help_text='The payout this compliance analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_analysis', to='wefund.traderpayout')),
            ],
            options={
                'verbose_name': 'Trader Payout Compliance Analysis',
                'verbose_name_plural': 'Trader Payout Compliance Analyses',
            },
        ),
        migrations.CreateModel(
            name='ComplianceResponsibleTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_time_utc', models.DateTimeField()),
                ('close_time_utc', models.DateTimeField(blank=True, null=True)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margin_at_open_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason_flagged', models.TextField()),
                ('breach_type', models.CharField(max_length=255)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_trades', to='wefund.traderpayoutcomplianceanalysis')),
            ],
            options={
                'verbose_name': 'Compliance Responsible Trade',
                'verbose_name_plural': 'Compliance Responsible Trades',
            },
        ),
    ]
