# Generated by Django 5.2.3 on 2025-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0050_traderpayoutcomplianceanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientkyc',
            name='rise_api_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientkyc',
            name='rise_invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientkyc',
            name='rise_invite_id',
            field=models.CharField(blank=True, help_text='The unique Rise invite identifier, if created', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientkyc',
            name='rise_invite_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientkyc',
            name='rise_webhook_response',
            field=models.JSONField(blank=True, help_text='Stores the webhook payload from Rise updates', null=True),
        ),
    ]
