# Generated by Django 5.2.3 on 2025-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0051_clientkyc_rise_api_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='exclude_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to exclude from payout (optional)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='traderpayout',
            name='exclude_reason',
            field=models.TextField(blank=True, help_text='Reason for excluding amount (optional)', null=True),
        ),
        migrations.AddField(
            model_name='traderpayout',
            name='is_custom_amount',
            field=models.BooleanField(default=False, help_text='Indicates if a custom payout amount was manually entered'),
        ),
    ]
