# Generated by Django 5.2.3 on 2025-09-05 02:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0053_internalnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_payout_delay_days', models.PositiveIntegerField(default=14)),
                ('subsequent_cycle_days', models.PositiveIntegerField(default=14)),
                ('min_net_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('base_share_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_policy', to='wefund.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutSplitTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_payout_number', models.PositiveIntegerField(help_text='Inclusive; starts at 1')),
                ('to_payout_number', models.PositiveIntegerField(blank=True, help_text='Inclusive; null = ∞', null=True)),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_tiers', to='wefund.payoutpolicy')),
            ],
            options={
                'ordering': ('from_payout_number',),
            },
        ),
    ]
