# Generated by Django 5.2.3 on 2025-09-05 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0054_payoutpolicy_payoutsplittier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconfiguration',
            name='base_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override: base share percent for custom config', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='config_type',
            field=models.CharField(choices=[('default', 'Default (Policy Driven)'), ('custom', 'Custom (Client Override)')], default='default', help_text='Whether this config follows system default policy or overrides with custom values', max_length=10),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='custom_cycle_days',
            field=models.PositiveIntegerField(blank=True, help_text='If cycle=custom_interval, number of days between payouts', null=True),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='custom_payout_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, help_text='If cycle=custom_days, list of days in month (e.g. [5, 20])', null=True, size=None),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='first_payout_delay_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override: days until first payout (if custom)', null=True),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='min_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override: minimum net amount after split (if custom)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payoutconfiguration',
            name='subsequent_cycle_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override: cycle days after first payout (if custom)', null=True),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('custom_days', 'Custom Days in Month'), ('custom_interval', 'Custom Interval')], default='monthly', help_text='How often the client can request a payout', max_length=20),
        ),
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='profit_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom fixed profit share % (leave blank to use policy/tier rules)', max_digits=5, null=True),
        ),
    ]
