# Generated by Django 5.2.3 on 2025-09-07 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0055_payoutconfiguration_base_share_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID to group logs of the same CSV upload')),
                ('row_number', models.PositiveIntegerField(help_text='Row number in CSV (or 1 for single import)')),
                ('email', models.EmailField(help_text='Email from CSV', max_length=254)),
                ('username', models.CharField(help_text='Username from CSV', max_length=150)),
                ('created_user', models.BooleanField(default=False, help_text='Whether user was newly created')),
                ('kyc_status', models.CharField(blank=True, max_length=50)),
                ('referred_by_email', models.EmailField(blank=True, max_length=254)),
                ('challenge_name', models.CharField(max_length=255)),
                ('phase_status', models.CharField(blank=True, max_length=100)),
                ('account_size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('broker_type', models.CharField(blank=True, max_length=50)),
                ('mt5_account_id', models.CharField(blank=True, max_length=50)),
                ('mt5_password', models.CharField(blank=True, max_length=100)),
                ('mt5_investor_password', models.CharField(blank=True, max_length=100)),
                ('payout_config_type', models.CharField(default='default', max_length=20)),
                ('next_withdrawal_date', models.DateTimeField(blank=True, null=True)),
                ('live_trading_start_date', models.DateField(blank=True, null=True)),
                ('profit_share_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_cycle', models.CharField(blank=True, max_length=20)),
                ('success', models.BooleanField(default=False, help_text='Did this row migrate successfully?')),
                ('errors', models.JSONField(blank=True, help_text='Validation or migration errors if failed', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
