# Generated by Django 5.2.3 on 2025-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0056_migrationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentmethod',
            name='rise_email',
            field=models.EmailField(blank=True, help_text='Rise account email for payout', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Crypto Wallet'), ('rise', 'Rise Payout')], help_text='Type of payment method (PayPal, Bank, Crypto)', max_length=20),
        ),
    ]
