# Generated by Django 5.2.3 on 2025-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0057_clientpaymentmethod_rise_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5trade',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
