# Generated by Django 5.2.3 on 2025-09-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0058_mt5trade_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('starting_equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ending_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('today_profit', models.DecimalField(decimal_places=2, default=0.0, help_text="Today's realized profit/loss (balance difference)", max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, help_text='Total realized profit/loss since account start', max_digits=15)),
                ('today_max_drawdown', models.DecimalField(decimal_places=2, default=0.0, help_text='Largest equity drop seen during this day', max_digits=15)),
                ('total_max_drawdown', models.DecimalField(decimal_places=2, default=0.0, help_text='Largest equity drop seen since account start', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='wefund.challengeenrollment')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
