# Generated by Django 5.2.3 on 2025-09-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0059_mt5dailysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mt5dailysnapshot',
            name='daily_loss_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="How much of today's max daily loss limit was used (0-100%).", max_digits=7),
        ),
        migrations.AddField(
            model_name='mt5dailysnapshot',
            name='total_loss_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='How much of total max loss limit was used (0-100%).', max_digits=7),
        ),
    ]
