# Generated by Django 5.2.3 on 2025-09-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0060_mt5dailysnapshot_daily_loss_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='released_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final total amount actually released to the trader', max_digits=12),
        ),
        migrations.AlterField(
            model_name='traderpayout',
            name='method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank', 'Bank Transfer'), ('crypto', 'Crypto'), ('rise', 'Rise Payout')], help_text='Chosen payout method', max_length=20),
        ),
    ]
