# Generated by Django 5.2.3 on 2025-09-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0061_traderpayout_released_fund_alter_traderpayout_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(unique=True)),
                ('plugin_version', models.CharField(max_length=20)),
                ('api_key_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_webhook_received', models.DateTimeField(blank=True, null=True)),
                ('total_webhooks_processed', models.PositiveIntegerField(default=0)),
                ('failed_webhooks_count', models.PositiveIntegerField(default=0)),
                ('rate_limit_exceeded_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WordPress Integration Setting',
                'verbose_name_plural': 'WordPress Integration Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='wefund_apir_endpoin_2d0163_idx'), models.Index(fields=['ip_address', 'created_at'], name='wefund_apir_ip_addr_443915_idx'), models.Index(fields=['response_status', 'created_at'], name='wefund_apir_respons_a56ab8_idx'), models.Index(fields=['created_at', 'endpoint'], name='wefund_apir_created_b4c359_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsedJWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('plugin_name', models.CharField(max_length=255)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=255)),
                ('webhook_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['token_jti'], name='wefund_used_token_j_f4cc18_idx'), models.Index(fields=['used_at'], name='wefund_used_used_at_08f464_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(db_index=True, max_length=100)),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('processing_stage', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], db_index=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook_id', 'created_at'], name='wefund_webh_webhook_af56c1_idx'), models.Index(fields=['order_id', 'created_at'], name='wefund_webh_order_i_16f48e_idx'), models.Index(fields=['status', 'created_at'], name='wefund_webh_status_169724_idx'), models.Index(fields=['processing_stage', 'status'], name='wefund_webh_process_db76bb_idx')],
            },
        ),
    ]
