# Generated by Django 5.2.3 on 2025-09-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0063_impersonationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Unique identifier (e.g., 'live_account', 'phase_one').", unique=True)),
                ('title', models.CharField(help_text='Display name of the certificate', max_length=100)),
                ('background_file', models.CharField(help_text="Relative path under static/certificates/ (e.g., 'Live Account Certificate.png')", max_length=255)),
                ('name_x', models.IntegerField()),
                ('name_y', models.IntegerField()),
                ('name_font_size', models.IntegerField(default=50)),
                ('date_x', models.IntegerField()),
                ('date_y', models.IntegerField()),
                ('date_font_size', models.IntegerField(default=36)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
