# Generated by Django 5.2.3 on 2025-09-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0064_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconfiguration',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_config', to='wefund.challengeenrollment'),
        ),
    ]
