# Generated by Django 5.2.3 on 2025-09-24 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0065_payoutconfiguration_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutconfiguration',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
