# Generated by Django 5.2.3 on 2025-09-26 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0067_payoutconfigimportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPasswordLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_password', models.CharField(help_text='The generated password (optional to store — consider encrypting or masking).', max_length=128)),
                ('length', models.PositiveIntegerField(help_text='Length of the generated password.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP of the admin who triggered generation.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device info of admin.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin who generated this password', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_password_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Password Log',
                'verbose_name_plural': 'Generated Password Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
