# Generated by Django 5.2.3 on 2025-10-02 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0068_generatedpasswordlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTActionPanelLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('activate_trading', 'Activate Trading'), ('disable_trading', 'Disable Trading'), ('enable_account', 'Enable Account'), ('disable_account', 'Disable Account'), ('change_group', 'Change Group'), ('retry_mt5_account_creation', 'Retry MT5 Account Creation')], help_text='Type of action performed', max_length=64)),
                ('target_id', models.CharField(help_text='ID of the target resource (e.g., MT5 account ID or Enrollment ID)', max_length=128)),
                ('extra_data', models.JSONField(blank=True, help_text='Optional payload/context (e.g., MT5 API response, old/new group name)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the admin performing the action', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='Admin/superuser who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mt_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MT Action Panel Log',
                'verbose_name_plural': 'MT Action Panel Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
