# Generated by Django 5.2.3 on 2025-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0069_mtactionpanellogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('phase', 'Phase'), ('payout', 'Payout')], help_text='Optional type of certificate: Phase or Payout', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='profitshare_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='profitshare_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='profitshare_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
