# Generated by Django 5.2.3 on 2025-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0070_certificatetemplate_certificate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconfiguration',
            name='first_payout_delay_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Exact minutes after purchase for first payout (e.g., 20160 = 14 days)', null=True),
        ),
    ]
