# Generated by Django 5.2.3 on 2025-10-07 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wefund', '0071_payoutconfiguration_first_payout_delay_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('status_change', 'Status Changed'), ('payout_approved', 'Payout Approved'), ('payout_paid', 'Payout Paid'), ('account_blocked', 'Account Blocked'), ('note_added', 'Note Added/Updated'), ('data_updated', 'Account Data Updated'), ('system_breach', 'System: Breach/Failure'), ('system_reset', 'System: Account Reset'), ('system_payout', 'System: Payout Sent')], help_text='Type of action taken.', max_length=50)),
                ('object_id', models.UUIDField(db_index=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed data, e.g., {"old_status": "in_progress", "new_status": "failed"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'wefund_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
