# Generated by Django 5.2.3 on 2025-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0071_payoutconfiguration_first_payout_delay_minutes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mt5dailysnapshot',
            unique_together={('enrollment', 'account_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='mt5dailysnapshot',
            index=models.Index(fields=['account_id', 'date'], name='wefund_mt5d_account_96cf16_idx'),
        ),
    ]
