# Generated by Django 5.2.3 on 2025-10-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0072_alter_mt5dailysnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpaymentmethod',
            name='crypto_type',
            field=models.CharField(blank=True, choices=[('usdt_trc20', 'USDT - TRC20'), ('usdt_erc20', 'USDT - ERC20'), ('usdc_erc20', 'USDC - ERC20'), ('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('other', 'Other')], help_text='Type of crypto wallet (e.g., USDT TRC20)', max_length=20, null=True),
        ),
    ]
