# Generated by Django 5.2.3 on 2025-10-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0072_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='extended_review_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of business days applied for extended review.', null=True),
        ),
        migrations.AddField(
            model_name='traderpayout',
            name='extended_review_until',
            field=models.DateTimeField(blank=True, help_text='When extended review ends and returns to pending.', null=True),
        ),
        migrations.AlterField(
            model_name='traderpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('extended_review', 'Extended Review')], default='pending', help_text='Payout request status', max_length=20),
        ),
    ]
