# Generated by Django 5.2.3 on 2025-10-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0073_alter_clientpaymentmethod_crypto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtactionpanellogs',
            name='action',
            field=models.CharField(choices=[('activate_trading', 'Activate Trading'), ('disable_trading', 'Disable Trading'), ('enable_account', 'Enable Account'), ('disable_account', 'Disable Account'), ('change_group', 'Change Group'), ('change_password', 'Change Password'), ('retry_mt5_account_creation', 'Retry MT5 Account Creation')], help_text='Type of action performed', max_length=64),
        ),
    ]
