# Generated by Django 5.2.3 on 2025-10-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0073_traderpayout_extended_review_days_and_more'),
        ('wefund', '0074_alter_mtactionpanellogs_action'),
    ]

    operations = [
    ]
