# Generated by Django 5.2.3 on 2025-10-12 14:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0075_merge_20251010_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5MigrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_mt5_id', models.CharField(max_length=20)),
                ('new_mt5_id', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('generate_password', models.BooleanField(default=False)),
                ('main_password', models.CharField(blank=True, max_length=100, null=True)),
                ('investor_password', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
