# Generated by Django 5.2.3 on 2025-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0076_mt5migrationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='breachhistory',
            name='previous_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
