# Generated by Django 5.2.3 on 2025-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0077_breachhistory_previous_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconfiguration',
            name='custom_next_withdrawal_datetime',
            field=models.DateTimeField(blank=True, help_text='Optional: Manually set next eligible withdrawal date and time (overrides automatic calculation if provided)', null=True),
        ),
    ]
