# Generated by Django 5.2.3 on 2025-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0079_redeemitem_rewardtask_redemption_rewardsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtask',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step guidance for clients to complete the task.'),
        ),
        migrations.AddField(
            model_name='rewardtask',
            name='url',
            field=models.URLField(blank=True, help_text='Optional external link related to this task (e.g., Telegram, Twitter, etc.)', max_length=500, null=True),
        ),
    ]
