# Generated by Django 5.2.3 on 2025-10-21 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0080_rewardtask_instructions_rewardtask_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCustomCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this custom commission is currently active')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Custom commission percentage (e.g. 15.00 for 15%). Leave blank to use tier rate.', max_digits=5, null=True)),
                ('fixed_amount_per_referral', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: fixed commission per approved referral (overrides percentage if set).', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or reason for this custom commission setup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.OneToOneField(help_text='Affiliate who has a custom commission setup', on_delete=django.db.models.deletion.CASCADE, related_name='custom_commission', to='wefund.affiliateprofile')),
            ],
        ),
    ]
