# Generated by Django 5.2.3 on 2025-10-24 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0081_affiliatecustomcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('kyc', 'KYC Update'), ('challenge', 'Challenge Update'), ('payout', 'Payout Info'), ('system', 'System Alert')], max_length=20)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Target user (null for global)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
