# Generated by Django 5.2.3 on 2025-10-24 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0082_schedulednotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulednotification',
            options={'ordering': ['-scheduled_for']},
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for management', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paused', 'Paused'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='scheduled_for',
            field=models.DateTimeField(help_text='Time when notification will be sent'),
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Target user (null = global notification)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
