# Generated by Django 5.2.3 on 2025-10-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0083_alter_schedulednotification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSLState',
            fields=[
                ('position_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.BigIntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('last_sl', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('last_seen_update_ts', models.BigIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['login', 'symbol'], name='wefund_posi_login_215fe5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StopLossChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.BigIntegerField(db_index=True)),
                ('login', models.BigIntegerField(db_index=True)),
                ('symbol', models.CharField(db_index=True, max_length=64)),
                ('side', models.CharField(max_length=4)),
                ('old_sl', models.DecimalField(decimal_places=10, max_digits=20)),
                ('new_sl', models.DecimalField(decimal_places=10, max_digits=20)),
                ('digits', models.IntegerField(default=5)),
                ('price_open', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('price_current', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('tp', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('storage', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('changed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.BigIntegerField(default=0)),
                ('expert_id', models.DecimalField(decimal_places=0, default=0, max_digits=30)),
                ('comment', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'indexes': [models.Index(fields=['position_id', 'changed_at'], name='wefund_stop_positio_5dec53_idx'), models.Index(fields=['login', 'symbol', 'changed_at'], name='wefund_stop_login_27d3c8_idx')],
                'unique_together': {('position_id', 'new_sl', 'changed_at')},
            },
        ),
    ]
