# Generated by Django 5.2.3 on 2025-10-25 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0084_positionslstate_stoplosschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden)'), ('active', 'Active (accepting requests)'), ('closed', 'Closed (not accepting new requests)'), ('released', 'Released to Production')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_kya', models.BooleanField(default=False)),
                ('requires_kyc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BetaFeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='requested', max_length=20)),
                ('request_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='wefund.betafeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feature', 'user')},
            },
        ),
    ]
