# Generated by Django 5.2.3 on 2025-10-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0085_betafeature_betafeatureaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='manual_tier_override',
            field=models.ForeignKey(blank=True, help_text='Admin can manually assign a tier. If set, this overrides auto tiering.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wefund.affiliatecommissiontier'),
        ),
    ]
