# Generated by Django 5.2.3 on 2025-11-03 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0086_affiliateprofile_manual_tier_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='eventlog',
            name='category',
            field=models.CharField(blank=True, choices=[('account', 'Account'), ('profile', 'Profile'), ('kyc', 'KYC / Verification'), ('challenge', 'Challenge'), ('mt5', 'MT5 / Trading'), ('payout', 'Payout'), ('affiliate', 'Affiliate'), ('offer', 'Offer / Coupon'), ('wallet', 'Wallet / Transaction'), ('risk', 'Risk / Breach'), ('system', 'System'), ('admin', 'Admin')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('account_created', 'Account Created'), ('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('email_updated', 'Email Updated'), ('name_updated', 'Name Updated'), ('profile_updated', 'Profile Updated'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('challenge_purchased', 'Challenge Purchased'), ('challenge_started', 'Challenge Started'), ('challenge_completed', 'Challenge Completed'), ('challenge_failed', 'Challenge Failed'), ('challenge_refunded', 'Challenge Refunded'), ('challenge_phase_changed', 'Challenge Phase Changed'), ('mt5_account_created', 'MT5 Account Created'), ('mt5_balance_updated', 'MT5 Balance Updated'), ('mt5_trade_opened', 'MT5 Trade Opened'), ('mt5_trade_closed', 'MT5 Trade Closed'), ('mt5_trading_disabled', 'MT5 Trading Disabled'), ('mt5_trading_enabled', 'MT5 Trading Enabled'), ('payout_requested', 'Payout Requested'), ('payout_approved', 'Payout Approved'), ('payout_rejected', 'Payout Rejected'), ('payout_paid', 'Payout Paid'), ('affiliate_registered', 'Affiliate Registered'), ('affiliate_sale_recorded', 'Affiliate Sale Recorded'), ('affiliate_commission_approved', 'Affiliate Commission Approved'), ('affiliate_tier_upgraded', 'Affiliate Tier Upgraded'), ('offer_created', 'Offer Created'), ('offer_expired', 'Offer Expired'), ('coupon_redeemed', 'Coupon Redeemed'), ('wallet_created', 'Wallet Created'), ('wallet_deposit', 'Wallet Deposit'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('wallet_balance_updated', 'Wallet Balance Updated'), ('soft_breach_detected', 'Soft Breach Detected'), ('hard_breach_detected', 'Hard Breach Detected'), ('breach_resolved', 'Breach Resolved'), ('system_error', 'System Error'), ('webhook_received', 'Webhook Received'), ('admin_action', 'Admin Action')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type'], name='wefund_even_event_t_a1b6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['category'], name='wefund_even_categor_687d96_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['timestamp'], name='wefund_even_timesta_1e7a54_idx'),
        ),
    ]
