# Generated by Django 5.2.3 on 2025-11-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0087_alter_eventlog_options_eventlog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('kyc', 'KYC / Verification'), ('challenge', 'Challenge'), ('payout', 'Payout'), ('affiliate', 'Affiliate'), ('offer', 'Offer / Coupon'), ('wallet', 'Wallet / Transaction'), ('system', 'System'), ('admin', 'Admin'), ('other', 'Other')], max_length=50, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('to_email', models.EmailField(max_length=254)),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='wefund.eventlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='wefund_emai_status_135ebd_idx'), models.Index(fields=['category'], name='wefund_emai_categor_ac4091_idx'), models.Index(fields=['created_at'], name='wefund_emai_created_2d48ed_idx')],
            },
        ),
    ]
