# Generated by Django 5.2.3 on 2025-11-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0088_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('support', 'Support'), ('affiliate', 'Affiliate'), ('risk', 'Risk Analyst'), ('admin', 'Admin'), ('content_creator', 'Content Creator'), ('discord_manager', 'Discord Manager')], default='client', max_length=20),
        ),
    ]
