# Generated by Django 5.2.3 on 2025-11-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0089_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='challenge_enrollment',
            field=models.ForeignKey(blank=True, help_text='If this event is linked to a specific challenge enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='wefund.challengeenrollment'),
        ),
    ]
