# Generated by Django 5.2.3 on 2025-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0096_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(blank=True, choices=[('account_created', 'Account Created'), ('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('password_changed', 'Password Changed'), ('email_updated', 'Email Updated'), ('name_updated', 'Name Updated'), ('profile_updated', 'Profile Updated'), ('kyc_initiated', 'KYC Initiated'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('challenge_purchased', 'Challenge Purchased'), ('challenge_started', 'Challenge Started'), ('challenge_completed', 'Challenge Completed'), ('challenge_failed', 'Challenge Failed'), ('challenge_refunded', 'Challenge Refunded'), ('challenge_phase_changed', 'Challenge Phase Changed'), ('challenge_config_updated', 'Challenge Configuration Updated'), ('challenge_blocked', 'Challenge Blocked'), ('challenge_deleted', 'Challenge Deleted'), ('mt5_account_created', 'MT5 Account Created'), ('mt5_balance_updated', 'MT5 Balance Updated'), ('mt5_trade_opened', 'MT5 Trade Opened'), ('mt5_trade_closed', 'MT5 Trade Closed'), ('mt5_trading_disabled', 'MT5 Trading Disabled'), ('mt5_trading_enabled', 'MT5 Trading Enabled'), ('mt5_deposit', 'MT5 Deposit'), ('mt5_withdrawal', 'MT5 Withdrawal'), ('mt5_trades_resynced', 'MT5 Trades Re-synced'), ('mt5_account_disabled', 'MT5 Account Disabled'), ('mt5_account_enabled', 'MT5 Account Enabled'), ('mt5_account_password_changed', 'MT5 Account Password Changed'), ('mt5_account_investor_password_changed', 'MT5 Investor Password Changed'), ('mt5_group_changed', 'MT5 Account Group Changed'), ('payout_created', 'Payout Created'), ('payout_requested', 'Payout Requested'), ('payout_approved', 'Payout Approved'), ('payout_rejected', 'Payout Rejected'), ('payout_paid', 'Payout Paid'), ('affiliate_registered', 'Affiliate Registered'), ('affiliate_sale_recorded', 'Affiliate Sale Recorded'), ('affiliate_commission_approved', 'Affiliate Commission Approved'), ('affiliate_tier_upgraded', 'Affiliate Tier Upgraded'), ('offer_created', 'Offer Created'), ('offer_expired', 'Offer Expired'), ('coupon_redeemed', 'Coupon Redeemed'), ('wallet_created', 'Wallet Created'), ('wallet_deposit', 'Wallet Deposit'), ('wallet_withdrawal', 'Wallet Withdrawal'), ('wallet_balance_updated', 'Wallet Balance Updated'), ('soft_breach_detected', 'Soft Breach Detected'), ('hard_breach_detected', 'Hard Breach Detected'), ('breach_resolved', 'Breach Resolved'), ('system_error', 'System Error'), ('webhook_received', 'Webhook Received'), ('admin_action', 'Admin Action')], max_length=100, null=True),
        ),
    ]
