# Generated by Django 5.2.3 on 2025-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0124_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='engine',
            field=models.CharField(blank=True, choices=[('order', 'Order Engine'), ('challenge', 'Challenge Engine'), ('kyc', 'KYC Engine'), ('risk', 'Risk Engine'), ('payout', 'Payout Engine')], help_text='Which internal engine triggered this event, if applicable.', max_length=50, null=True),
        ),
    ]
