# Generated by Django 5.2.3 on 2025-11-12 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0133_alter_eventlog_category_alter_eventlog_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
