# Generated by Django 5.2.3 on 2025-11-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0135_alter_eventlog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtask',
            name='example_image',
            field=models.ImageField(blank=True, help_text='Optional example image shown to clients when completing this task.', null=True, upload_to='reward_tasks/examples/'),
        ),
        migrations.AddField(
            model_name='rewardtask',
            name='requires_url_submission',
            field=models.BooleanField(default=False, help_text='If enabled, the user must submit a URL when completing this task.'),
        ),
    ]
