# Generated by Django 5.2.3 on 2025-11-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0136_rewardtask_example_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtask',
            name='example_image',
            field=models.URLField(blank=True, help_text='Example image URL stored on BunnyCDN.', max_length=500, null=True),
        ),
    ]
