# Generated by Django 5.2.3 on 2025-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0137_alter_rewardtask_example_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsubmission',
            name='proof_image',
            field=models.URLField(blank=True, help_text='Screenshot proof uploaded via BunnyCDN.', max_length=500, null=True),
        ),
    ]
