# Generated by Django 5.2.3 on 2025-11-29 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0138_rewardsubmission_proof_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mt5_account_id', models.CharField(blank=True, help_text='MT5 account used for this payout period.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='\n        Computed metrics, e.g.:\n        {\n          "total_trades": 42,\n          "win_rate": 0.57,\n          "avg_rr": 1.8,\n          "max_drawdown_pct": -6.2,\n          "avg_holding_time_minutes": 45.2,\n          "symbol_exposure": {"XAUUSD": 0.65, "NAS100": 0.35},\n          "session_distribution": {"london": 22, "ny": 15, "asia": 5},\n          ...\n        }\n        ')),
                ('trade_samples', models.JSONField(blank=True, default=dict, help_text='\n        Example:\n        {\n          "period_start": "2025-11-01T00:00:00Z",\n          "period_end": "2025-11-15T12:00:00Z",\n          "trades": [\n            {\n              "ticket": 123456,\n              "symbol": "XAUUSD",\n              "cmd": "buy",\n              "volume": 1.0,\n              "open_time": "...",\n              "close_time": "...",\n              "pnl": 250.50,\n              "rr": 2.4,\n              "holding_minutes": 38,\n              "is_news_time": false\n            },\n            ...\n          ]\n        }\n        ')),
                ('llm_model', models.CharField(default='gpt-5.1', help_text='Model used for this analysis.', max_length=50)),
                ('llm_prompt_version', models.CharField(default='ai-analysis-v2-001', help_text='Internal version of the prompt/template used.', max_length=50)),
                ('llm_request_payload', models.JSONField(blank=True, default=dict, help_text='Exact JSON payload we sent to GPT (for debugging/audit).')),
                ('llm_raw_response', models.JSONField(blank=True, default=dict, help_text='Raw JSON output from GPT before parsing/mapping.')),
                ('ai_summary', models.TextField(blank=True, help_text="Short narrative summary of trader's overall behaviour.", null=True)),
                ('ai_trading_style', models.JSONField(blank=True, default=dict, help_text='\n        GPT view of trading style, e.g.:\n        {\n          "style": "intraday swing",\n          "timeframes": ["M15", "H1"],\n          "session_focus": ["London", "NY"],\n          "description": "Prefers XAUUSD intraday swings with moderate risk."\n        }\n        ')),
                ('ai_risk_profile', models.JSONField(blank=True, default=dict, help_text='\n        {\n          "risk_score": 68,\n          "risk_level": "medium-high",\n          "key_risks": ["aggressive position sizing", "occasional overtrading"],\n          "drawdown_comment": "Max DD remains within program limits but close to threshold."\n        }\n        ')),
                ('ai_consistency', models.JSONField(blank=True, default=dict, help_text='\n        {\n          "lot_size_consistency": "good",\n          "session_consistency": "medium",\n          "rule_violations": ["few clustered trades <60s apart"],\n          "comment": "Mostly consistent but some bursts of impulsive behaviour."\n        }\n        ')),
                ('ai_recommendations', models.JSONField(blank=True, default=dict, help_text='\n        Concrete suggestions for the trader & internal notes:\n        {\n          "for_trader": ["Reduce lot size after losing streak", ...],\n          "for_prop_firm": ["Consider lowering max risk per trade for next phase", ...]\n        }\n        ')),
                ('recommendation', models.CharField(blank=True, choices=[('approve', 'Approve Payout'), ('reject', 'Reject Payout'), ('manual_review', 'Manual Review Required')], help_text='AI suggested decision (human must still decide).', max_length=20, null=True)),
                ('recommendation_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='0.00–1.00 confidence score from AI.', max_digits=4, null=True)),
                ('recommendation_rationale', models.TextField(blank=True, help_text='Why the AI made this recommendation.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_ai_analyses', to='wefund.challengeenrollment')),
                ('payout', models.OneToOneField(help_text='The payout this AI analysis belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_v2', to='wefund.traderpayout')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_ai_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskScanReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report', models.JSONField(default=dict, help_text='Complete structured Risk Engine v2 output.')),
                ('global_score', models.IntegerField(default=0)),
                ('max_severity', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.OneToOneField(help_text='The payout this risk report belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='risk_scan', to='wefund.traderpayout')),
                ('reran_by', models.ForeignKey(blank=True, help_text='Admin who re-triggered the scan.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
