# Generated by Django 5.2.3 on 2025-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0139_payoutaianalysis_riskscanreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderpayout',
            name='conversion_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
