# Generated by Django 5.2.3 on 2025-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0140_traderpayout_conversion_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaianalysis',
            name='adjusted_payout',
            field=models.JSONField(blank=True, default=dict, help_text='Original vs excluded profit and recommended payout.'),
        ),
        migrations.AddField(
            model_name='payoutaianalysis',
            name='overall_classification',
            field=models.CharField(blank=True, help_text='Compliant, Soft Breach, or Hard Breach', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payoutaianalysis',
            name='violations',
            field=models.JSONField(blank=True, default=list, help_text='List of detected rule violations with details.'),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='ai_consistency',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='ai_risk_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='ai_trading_style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='llm_model',
            field=models.CharField(default='gpt-5.1', max_length=50),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='llm_prompt_version',
            field=models.CharField(default='ai-analysis-v2-001', max_length=50),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='llm_raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='llm_request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('approve', 'Approve Payout'), ('reject', 'Reject Payout'), ('manual_review', 'Manual Review Required')], help_text='approve / reject / manual_review', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='recommendation_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='recommendation_rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payoutaianalysis',
            name='trade_samples',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
