# Generated by Django 5.2.3 on 2025-12-04 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0141_payoutaianalysis_adjusted_payout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutConsistencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=50)),
                ('analysis', models.JSONField()),
                ('verdict', models.CharField(max_length=20)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payout_status', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_reports', to='wefund.challengeenrollment')),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_report', to='wefund.traderpayout')),
            ],
        ),
    ]
