# Generated by Django 5.2.3 on 2025-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0142_payoutconsistencyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconsistencyreport',
            name='ai_parsed_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutconsistencyreport',
            name='ai_raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutconsistencyreport',
            name='ai_request',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
