# Generated by Django 5.2.3 on 2025-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0143_payoutconsistencyreport_ai_parsed_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutconsistencyreport',
            name='final_net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payoutconsistencyreport',
            name='final_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
