# Generated by Django 5.2.3 on 2025-12-09 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0144_payoutconsistencyreport_final_net_profit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='competitions/banners/')),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.TextField()),
                ('organizer_name', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('leverage', models.CharField(max_length=20)),
                ('mt5_group', models.CharField(max_length=255)),
                ('allowed_symbols', models.JSONField(blank=True, null=True)),
                ('min_trades_to_qualify', models.PositiveIntegerField(blank=True, null=True)),
                ('scoring_metric', models.CharField(choices=[('growth_percent', '% Growth')], default='growth_percent', max_length=50)),
                ('rules_markdown', models.TextField()),
                ('use_global_rules', models.BooleanField(default=True)),
                ('prize_pool_text', models.CharField(max_length=255)),
                ('entry_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('invite', 'Invite Only')], max_length=20)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_create_mt5', models.BooleanField(default=True)),
                ('enforce_single_entry', models.BooleanField(default=True)),
                ('allow_test_users', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefund.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionPrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank_from', models.PositiveIntegerField()),
                ('rank_to', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='wefund.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wefund.competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionRankingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mt5_login', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
                ('growth_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_trades', models.PositiveIntegerField()),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='wefund.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('competition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mt5_login', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disqualified', 'Disqualified'), ('completed', 'Completed')], default='active', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='wefund.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
