# Generated by Django 5.2.3 on 2025-12-09 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0145_competition_competitioninvite_competitionprize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('mdl', 'Max Daily Loss'), ('mtl', 'Max Total Loss'), ('mtd', 'Max Trades Per Day'), ('pr', 'Profit Requirement'), ('min_days', 'Minimum Trading Days'), ('max_lot', 'Max Lot Size'), ('consistency', 'Consistency Rule')], max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value_type', models.CharField(choices=[('percent', 'Percentage'), ('amount', 'Fixed Amount'), ('count', 'Count'), ('boolean', 'Boolean')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_rules', to='wefund.competition')),
            ],
            options={
                'unique_together': {('competition', 'rule_type')},
            },
        ),
    ]
