# Generated by Django 5.2.3 on 2025-12-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0146_competitionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner',
            field=models.URLField(max_length=500),
        ),
    ]
