# Generated by Django 5.2.3 on 2025-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0147_alter_competition_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
