# Generated by Django 5.2.3 on 2025-12-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0148_alter_competition_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='challenge',
            field=models.ForeignKey(blank=True, help_text='Optional challenge to be awarded to winners', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='wefund.challenge'),
        ),
    ]
