# Generated by Django 5.2.3 on 2025-12-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0149_competition_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionregistration',
            name='challenge_enrollment',
            field=models.ForeignKey(blank=True, help_text='Set only if this competition grants a challenge to the trader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_registrations', to='wefund.challengeenrollment'),
        ),
    ]
