# Generated by Django 5.2.3 on 2025-12-16 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0150_competitionregistration_challenge_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='MARTINGALE, GRID, PYRAMID, BOT_TRADING', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('AUTO_REJECT', 'Auto Reject'), ('REVIEW', 'Manual Review'), ('WARNING', 'Warning Only')], max_length=20)),
                ('detection_guidelines', models.TextField(help_text='Natural language rules injected into AI prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['severity', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AIRiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('account_step', models.CharField(choices=[('step_1', 'Step 1'), ('step_2', 'Step 2')], max_length=10)),
                ('trade_data', models.JSONField(help_text='Exact trades sent to AI')),
                ('account_snapshot', models.JSONField(help_text='Balance, equity, dates, etc')),
                ('consistency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('consistency_result', models.CharField(blank=True, max_length=30, null=True)),
                ('ai_model', models.CharField(max_length=100)),
                ('ai_prompt_version', models.CharField(max_length=20)),
                ('ai_analysis_text', models.TextField()),
                ('ai_recommendation', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('MANUAL_REVIEW', 'Manual Review')], max_length=20)),
                ('ai_patterns_detected', models.JSONField(default=list, help_text='List of detected prohibited patterns')),
                ('ai_confidence', models.DecimalField(decimal_places=2, help_text='AI confidence %', max_digits=5)),
                ('final_decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('APPROVE_WITH_DEDUCTIONS', 'Approve With Deductions')], max_length=32, null=True)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_risk_analysis', to='wefund.traderpayout')),
            ],
        ),
        migrations.CreateModel(
            name='AIRiskReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('APPROVE_WITH_DEDUCTIONS', 'Approve With Deductions')], max_length=32)),
                ('human_agrees_with_ai', models.BooleanField()),
                ('human_reasoning', models.TextField()),
                ('patterns_confirmed', models.JSONField(default=list)),
                ('patterns_rejected', models.JSONField(default=list)),
                ('patterns_added', models.JSONField(default=list)),
                ('review_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('training_priority', models.PositiveIntegerField(default=0)),
                ('is_training_example', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='wefund.airiskanalysis')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='airiskanalysis',
            index=models.Index(fields=['status'], name='wefund_airi_status_4f4a15_idx'),
        ),
        migrations.AddIndex(
            model_name='airiskanalysis',
            index=models.Index(fields=['account_id'], name='wefund_airi_account_0d1761_idx'),
        ),
        migrations.AddIndex(
            model_name='airiskanalysis',
            index=models.Index(fields=['ai_recommendation'], name='wefund_airi_ai_reco_8b26b5_idx'),
        ),
        migrations.AddIndex(
            model_name='airiskreviewfeedback',
            index=models.Index(fields=['human_agrees_with_ai'], name='wefund_airi_human_a_948fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='airiskreviewfeedback',
            index=models.Index(fields=['training_priority'], name='wefund_airi_trainin_929f26_idx'),
        ),
        migrations.AddIndex(
            model_name='airiskreviewfeedback',
            index=models.Index(fields=['is_training_example'], name='wefund_airi_is_trai_ac2caf_idx'),
        ),
    ]
