# Generated by Django 5.2.3 on 2025-12-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0151_airiskrule_airiskanalysis_airiskreviewfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airiskanalysis',
            name='ai_raw_request',
            field=models.JSONField(blank=True, help_text='Full raw request payload sent to RunPod', null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='ai_raw_response',
            field=models.JSONField(blank=True, help_text='Full raw response received from RunPod', null=True),
        ),
    ]
