# Generated by Django 5.2.3 on 2025-12-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0152_airiskanalysis_ai_raw_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airiskanalysis',
            name='ai_confidence',
            field=models.DecimalField(decimal_places=2, help_text='AI confidence percentage (0–100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='consistency_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Risk engine global score (can exceed 1000)', max_digits=10, null=True),
        ),
    ]
