# Generated by Django 5.2.3 on 2025-12-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0153_alter_airiskanalysis_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airiskanalysis',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='runpod_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='runpod_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='runpod_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
