# Generated by Django 5.2.3 on 2025-12-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0154_airiskanalysis_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airiskanalysis',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='airiskanalysis',
            name='runpod_error',
        ),
        migrations.RemoveField(
            model_name='airiskanalysis',
            name='runpod_job_id',
        ),
        migrations.RemoveField(
            model_name='airiskanalysis',
            name='runpod_status',
        ),
    ]
