# Generated by Django 5.2.3 on 2025-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0155_remove_airiskanalysis_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airiskanalysis',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='runpod_job_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='airiskanalysis',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='ai_analysis_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence percentage (0–100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='ai_patterns_detected',
            field=models.JSONField(blank=True, default=list, help_text='List of detected prohibited patterns'),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('MANUAL_REVIEW', 'Manual Review')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airiskanalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
