# Generated by Django 5.2.3 on 2025-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0156_airiskanalysis_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtask',
            name='feature_image',
            field=models.URLField(blank=True, help_text='Feature image URL (e.g., banner/thumbnail) stored on BunnyCDN.', max_length=500, null=True),
        ),
    ]
