# Generated by Django 5.2.3 on 2025-12-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0157_rewardtask_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='organizer_logo',
            field=models.URLField(blank=True, help_text='Logo URL of the competition organizer', max_length=500, null=True),
        ),
    ]
