# Generated by Django 5.2.3 on 2026-01-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0158_competition_organizer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpayout',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
