# Generated by Django 5.2.3 on 2026-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0160_alter_breachhistory_breached_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breachhistory',
            name='breached_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
