# Generated by Django 5.2.3 on 2026-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0162_alter_traderpayout_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderpayout',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
