# Generated by Django 5.2.3 on 2026-02-04 14:21
# Modified to use JSONField instead of ArrayField for SQLite compatibility

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0165_alter_breachhistory_breached_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'book', 'shield', 'dollar')", max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_enabled', models.BooleanField(default=True, help_text='Master switch for AI responses globally')),
                ('ai_greeting', models.TextField(default='Hey there! Please describe your request in detail.', help_text='Default greeting message when conversation starts')),
                ('ai_system_prompt', models.TextField(blank=True, help_text='Base system prompt for AI (merged with dynamic context)')),
                ('simple_model', models.CharField(default='gemini-2.5-flash-lite', help_text='Fast model for simple queries (cost-optimized)', max_length=100)),
                ('complex_model', models.CharField(default='gemini-2.5-flash', help_text='Advanced model for complex queries (better reasoning)', max_length=100)),
                ('complexity_threshold', models.IntegerField(default=100, help_text='Character count threshold to switch from simple to complex model')),
                ('read_actions_enabled', models.BooleanField(default=True, help_text='Allow AI to reference user account data')),
                ('write_actions_enabled', models.BooleanField(default=False, help_text='Allow AI to modify data (future feature)')),
                ('allowed_write_actions', models.JSONField(blank=True, default=list, help_text='List of write actions AI can perform')),
                ('confidence_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.85'), help_text='Minimum confidence for auto-response (0-1)', max_digits=3)),
                ('escalation_keywords', models.JSONField(blank=True, default=list, help_text='Keywords that trigger immediate escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support AI Configuration',
                'verbose_name_plural': 'Support AI Configuration',
            },
        ),
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_login', models.CharField(blank=True, help_text='Optional MT5 account login for context', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], db_index=True, default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('ai_enabled', models.BooleanField(default=True, help_text='AI responses enabled for this conversation')),
                ('attachments_enabled', models.BooleanField(default=False, help_text='File attachments allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, help_text='First AI/agent response time', null=True)),
                ('agent_takeover_at', models.DateTimeField(blank=True, help_text='When human agent took over', null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('deescalation_attempted', models.BooleanField(default=False, help_text='AI attempted de-escalation')),
                ('needs_human_review', models.BooleanField(db_index=True, default=False, help_text='Flagged for human review')),
                ('subject', models.CharField(blank=True, help_text='Auto-generated or manual subject line', max_length=255)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Soft delete for user')),
                ('source', models.CharField(choices=[('widget', 'Widget'), ('discord', 'Discord'), ('email', 'Email')], default='widget', max_length=20)),
                ('external_channel_id', models.CharField(blank=True, help_text='Discord channel ID or email thread ID', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (emotional state, tags, etc.)')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_conversations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI'), ('agent', 'Agent')], db_index=True, max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Staff-only note, hidden from user')),
                ('attachment_url', models.URLField(blank=True, help_text='BunnyCDN URL of attachment', max_length=500, null=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_type', models.CharField(blank=True, help_text='MIME type', max_length=100, null=True)),
                ('attachment_scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('malicious', 'Malicious'), ('error', 'Error')], default='pending', help_text='Virus scan result', max_length=20)),
                ('emotional_context', models.JSONField(blank=True, help_text='Emotional analysis data (level, indicators, etc.)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='AI model used, tokens, quality flags, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wefund.supportconversation')),
                ('sender', models.ForeignKey(blank=True, help_text='User or agent who sent the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('wrong_info', 'Wrong Information'), ('inappropriate', 'Inappropriate')], max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('needed_correction', models.BooleanField(default=False)),
                ('correction_made', models.TextField(blank=True, help_text='The correct response')),
                ('agent_notes', models.TextField(blank=True)),
                ('should_be_training_example', models.BooleanField(default=False, help_text='Include in future training datasets')),
                ('training_priority', models.IntegerField(default=0, help_text='Higher = more important')),
                ('issue_categories', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='wefund.supportconversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='wefund.supportmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown supported')),
                ('search_keywords', models.JSONField(blank=True, default=list, help_text='Manual keywords for search matching')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='wefund.faqcollection')),
            ],
            options={
                'ordering': ['collection__display_order', 'display_order', 'title'],
                'indexes': [models.Index(fields=['collection', 'is_active'], name='wefund_faqa_collect_39c50d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['user', '-created_at'], name='wefund_supp_user_id_feb099_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', 'needs_human_review'], name='wefund_supp_status_ab7966_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['-last_message_at'], name='wefund_supp_last_me_1d368d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='wefund_supp_convers_596143_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender_type', 'created_at'], name='wefund_supp_sender__689321_idx'),
        ),
    ]
