# Generated by Django 5.2.3 on 2026-02-08 15:10

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0167_fix_faqarticle_search_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCalendarSyncSchedule',
            fields=[
                ('id', models.CharField(default='economic_calendar', max_length=50, primary_key=True, serialize=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_interval_hours', models.PositiveIntegerField(default=24)),
                ('is_enabled', models.BooleanField(default=True)),
                ('schedule_hour', models.PositiveIntegerField(default=0, help_text='Hour (UTC) to run daily sync')),
                ('last_sync_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economic Calendar Sync Schedule',
                'verbose_name_plural': 'Economic Calendar Sync Schedules',
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('event_datetime', models.DateTimeField(db_index=True)),
                ('time_window_minutes', models.PositiveIntegerField(default=5)),
                ('affected_symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Trading symbols affected by this event', size=None)),
                ('actual_value', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_value', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_value', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('forex_factory', 'Forex Factory')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economic Event',
                'verbose_name_plural': 'Economic Events',
                'ordering': ['event_datetime'],
                'unique_together': {('event_name', 'event_datetime', 'source')},
            },
        ),
    ]
