# Generated by Django 5.2.3 on 2026-02-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0168_economic_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardtask',
            name='expire_action',
            field=models.CharField(choices=[('mark_expired', 'Mark as expired'), ('archive', 'Archive'), ('inactivate', 'Set inactive')], default='mark_expired', help_text='What to do when expires_at is reached.', max_length=20),
        ),
        migrations.AddField(
            model_name='rewardtask',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional: task expires at this time (leave empty for no expiry).', null=True),
        ),
        migrations.AddField(
            model_name='rewardtask',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Optional: task becomes available at this time (leave empty for immediate).', null=True),
        ),
    ]
