# Generated by Django 5.2.3 on 2026-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0169_rewardtask_expire_action_rewardtask_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemitem',
            name='expire_action',
            field=models.CharField(choices=[('deactivate', 'Set inactive'), ('archive', 'Archive')], default='deactivate', help_text='What to do once expires_at is reached.', max_length=20),
        ),
        migrations.AddField(
            model_name='redeemitem',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional: item stops being redeemable after this time.', null=True),
        ),
        migrations.AddField(
            model_name='redeemitem',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If archived, item is hidden from all redemption listings.'),
        ),
        migrations.AddField(
            model_name='redeemitem',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Optional: item becomes redeemable starting at this time.', null=True),
        ),
    ]
