# Generated by Django 5.2.3 on 2026-02-11 09:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0170_redeemitem_expire_action_redeemitem_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAIConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_enabled', models.BooleanField(default=True, help_text='Master switch for Admin AI Assistant')),
                ('ai_greeting', models.TextField(default="Hello! I'm your AI assistant. I can help you look up enrollments, traders, payouts, MT5 data, and answer policy questions. What do you need?", help_text='Greeting message when admin starts a conversation')),
                ('ai_system_prompt', models.TextField(blank=True, help_text='Additional system prompt merged with base instructions')),
                ('simple_model', models.CharField(default='gemini-2.5-flash-lite', help_text='Fast model for simple queries (cheapest)', max_length=100)),
                ('standard_model', models.CharField(default='gemini-2.5-flash', help_text='Standard model for moderate complexity', max_length=100)),
                ('pro_model', models.CharField(default='gemini-2.5-pro', help_text='Pro model for complex multi-step reasoning', max_length=100)),
                ('complexity_threshold_standard', models.IntegerField(default=4, help_text='Minimum complexity score (1-7) to use standard model')),
                ('complexity_threshold_pro', models.IntegerField(default=6, help_text='Minimum complexity score (1-7) to use pro model')),
                ('read_actions_enabled', models.BooleanField(default=True, help_text='Allow AI to execute read/lookup actions')),
                ('write_actions_enabled', models.BooleanField(default=False, help_text='Allow AI to execute MT5 write operations')),
                ('allowed_read_actions', models.JSONField(blank=True, default=list, help_text='List of allowed read action names')),
                ('allowed_write_actions', models.JSONField(blank=True, default=list, help_text='List of allowed write action names')),
                ('confirmation_required_actions', models.JSONField(blank=True, default=list, help_text='Write actions that require admin confirmation before execution')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum output tokens for AI responses')),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.40'), help_text='AI temperature (0-1). Lower = more deterministic', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin AI Configuration',
                'verbose_name_plural': 'Admin AI Configuration',
            },
        ),
        migrations.CreateModel(
            name='AdminAIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('general', 'General'), ('enrollment', 'Enrollment'), ('trader', 'Trader'), ('payout', 'Payout'), ('order', 'Order')], default='general', max_length=20)),
                ('context_id', models.CharField(blank=True, help_text='UUID of the entity being viewed (enrollment, trader, etc.)', max_length=255, null=True)),
                ('context_url', models.CharField(blank=True, default='', help_text='CRM page URL where conversation was started', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ai', 'AI'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('complexity_score', models.IntegerField(blank=True, help_text='Message complexity score (1-7)', null=True)),
                ('action_executed', models.CharField(blank=True, help_text='Tool function name that was executed', max_length=100, null=True)),
                ('action_params', models.JSONField(blank=True, help_text='Parameters passed to the tool', null=True)),
                ('action_result', models.JSONField(blank=True, help_text='Result returned from the tool', null=True)),
                ('action_status', models.CharField(blank=True, choices=[('success', 'Success'), ('error', 'Error'), ('pending_confirmation', 'Pending Confirmation'), ('processing', 'Processing'), ('cancelled', 'Cancelled')], max_length=30, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wefund.adminaiconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAIFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_positive', models.BooleanField(help_text='True = thumbs up, False = thumbs down')),
                ('issue_type', models.CharField(choices=[('wrong_data', 'Wrong Data'), ('wrong_action', 'Wrong Action'), ('poor_explanation', 'Poor Explanation'), ('hallucination', 'Hallucination'), ('helpful', 'Helpful'), ('other', 'Other')], default='other', max_length=30)),
                ('correction_text', models.TextField(blank=True, help_text='The correct response or data')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_ai_feedback_given', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='wefund.adminaiconversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='wefund.adminaimessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAITrainingExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='Example user question')),
                ('ideal_response', models.TextField(help_text='Ideal AI response')),
                ('weight', models.IntegerField(default=5, help_text='Importance weight (1-10). Higher = more likely to be included')),
                ('issue_type', models.CharField(blank=True, help_text='Category of the issue this example addresses', max_length=30, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing examples')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_feedback', models.ForeignKey(blank=True, help_text='Feedback that generated this training example', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_examples', to='wefund.adminaifeedback')),
            ],
            options={
                'ordering': ['-weight', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminaiconversation',
            index=models.Index(fields=['admin_user', '-created_at'], name='wefund_admi_admin_u_75337c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaiconversation',
            index=models.Index(fields=['context_type', 'context_id'], name='wefund_admi_context_4ac5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='wefund_admi_convers_2eea90_idx'),
        ),
    ]
