# Generated by Django 5.2.3 on 2026-02-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0171_adminaiconfig_adminaiconversation_adminaimessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingReportConfig',
            fields=[
                ('id', models.CharField(default='trading_report', max_length=50, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True, default='')),
                ('slack_enabled', models.BooleanField(default=False)),
                ('auto_weekly', models.BooleanField(default=True)),
                ('auto_monthly', models.BooleanField(default=True)),
                ('weekly_day', models.IntegerField(default=1, help_text='Day of week for weekly report (1=Monday, 7=Sunday)')),
                ('monthly_day', models.IntegerField(default=1, help_text='Day of month for monthly report (1-28)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Report Configuration',
            },
        ),
        migrations.CreateModel(
            name='TradingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(help_text='Full report data (all 6 metrics, top 5 each)')),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('slack_sent', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
