# Generated by Django 5.2.3 on 2026-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0172_tradingreportconfig_tradingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemitem',
            name='max_per_user',
            field=models.PositiveIntegerField(default=0, help_text='Max times a single client can redeem this item. 0 = unlimited.'),
        ),
    ]
