# Generated by Django 5.2.3 on 2026-02-18 08:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0173_redeemitem_max_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreachEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(help_text='UTC aware capture time (Django)')),
                ('broker_time', models.DateTimeField(blank=True, help_text='Broker/MT5 server time if available', null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('free_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('start_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('max_loss_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equity_payload', models.JSONField(blank=True, null=True)),
                ('positions_payload', models.JSONField(blank=True, null=True)),
                ('positions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='wefund.breachhistory')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_evidences', to='wefund.challengeenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='BreachEvidencePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=8)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=18)),
                ('open_price', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('swap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('magic', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='wefund.breachevidence')),
            ],
        ),
        migrations.AddIndex(
            model_name='breachevidence',
            index=models.Index(fields=['enrollment', 'captured_at'], name='wefund_brea_enrollm_7d52c1_idx'),
        ),
        migrations.AddIndex(
            model_name='breachevidence',
            index=models.Index(fields=['account_id', 'captured_at'], name='wefund_brea_account_21d4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='breachevidenceposition',
            index=models.Index(fields=['evidence', 'ticket'], name='wefund_brea_evidenc_dcfd79_idx'),
        ),
        migrations.AddIndex(
            model_name='breachevidenceposition',
            index=models.Index(fields=['symbol'], name='wefund_brea_symbol_d581f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='breachevidenceposition',
            constraint=models.UniqueConstraint(fields=('evidence', 'ticket'), name='uniq_evidence_ticket'),
        ),
    ]
