# Generated by Django 5.2.3 on 2026-02-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0174_breachevidence_breachevidenceposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnote',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('risk', 'Risk'), ('consistency', 'Consistency'), ('device', 'Device/IP'), ('copy_trading', 'Copy Trading'), ('manual_review', 'Manual Review')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
