# Generated by Django 5.2.3 on 2026-02-16 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0175_internalnote_category_internalnote_is_high_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('strategy', 'Strategy'), ('setup', 'Setup'), ('mistake', 'Mistake'), ('emotion', 'Emotion'), ('market_condition', 'Market Condition'), ('custom', 'Custom')], max_length=20)),
                ('color', models.CharField(default='#28BFFF', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=30)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tag Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_tag_enabled', models.BooleanField(default=True)),
                ('ai_insights_enabled', models.BooleanField(default=True)),
                ('daily_reminder_enabled', models.BooleanField(default=False)),
                ('default_chart_period', models.CharField(default='30d', max_length=10)),
                ('calendar_view', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('breach_alert_threshold', models.PositiveSmallIntegerField(default=80, help_text='Alert at this % of limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#28BFFF', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='wefund.tagcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JournalInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('daily_summary', 'Daily Summary'), ('weekly_report', 'Weekly Report'), ('monthly_report', 'Monthly Report'), ('pattern_detection', 'Pattern Detection'), ('chat_response', 'Chat Response')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('question', models.TextField(blank=True, help_text='For chat Q&A')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('generation_time_ms', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_insights', to='wefund.challengeenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'insight_type'], name='wefund_jour_user_id_ecdb9a_idx'), models.Index(fields=['prompt_hash'], name='wefund_jour_prompt__8d160e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentorAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('comment', 'Comment')], default='read_only', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_access', to=settings.AUTH_USER_MODEL)),
                ('shared_enrollments', models.ManyToManyField(blank=True, related_name='mentor_shares', to='wefund.challengeenrollment')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trader', 'mentor')},
            },
        ),
        migrations.CreateModel(
            name='TradeJournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('setup_description', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('planned_entry', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('planned_sl', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('planned_tp', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('followed_plan', models.BooleanField(blank=True, null=True)),
                ('emotional_state', models.CharField(blank=True, choices=[('confident', 'Confident'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('frustrated', 'Frustrated'), ('revenge', 'Revenge Trading'), ('fomo', 'FOMO'), ('bored', 'Bored')], max_length=20)),
                ('screenshot_entry', models.URLField(blank=True, max_length=500)),
                ('screenshot_exit', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='wefund.challengeenrollment')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='wefund.mt5trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='wefund.tradetag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'enrollment'], name='wefund_trad_user_id_078dee_idx'), models.Index(fields=['created_at'], name='wefund_trad_created_2f4ea0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pre_session_notes', models.TextField(blank=True)),
                ('post_session_notes', models.TextField(blank=True)),
                ('key_lessons', models.TextField(blank=True)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('discipline_score', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('emotional_state_start', models.CharField(blank=True, choices=[('confident', 'Confident'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('frustrated', 'Frustrated'), ('revenge', 'Revenge Trading'), ('fomo', 'FOMO'), ('bored', 'Bored')], max_length=20)),
                ('emotional_state_end', models.CharField(blank=True, choices=[('confident', 'Confident'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('frustrated', 'Frustrated'), ('revenge', 'Revenge Trading'), ('fomo', 'FOMO'), ('bored', 'Bored')], max_length=20)),
                ('market_conditions', models.CharField(blank=True, choices=[('trending', 'Trending'), ('ranging', 'Ranging'), ('volatile', 'Volatile'), ('low_vol', 'Low Volatility'), ('news_driven', 'News Driven')], max_length=20)),
                ('followed_rules', models.BooleanField(blank=True, null=True)),
                ('rule_violations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to='wefund.challengeenrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'enrollment', 'date')},
            },
        ),
    ]
