# Generated by Django 5.2.3 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0177_seed_journal_tags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalinsight',
            constraint=models.UniqueConstraint(fields=('user', 'enrollment', 'insight_type', 'period_start'), name='unique_journal_insight_per_period'),
        ),
    ]
