# Generated by Django 5.2.3 on 2026-02-17 07:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0179_journalsharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Markdown-formatted release notes')),
                ('version', models.CharField(blank=True, max_length=30)),
                ('release_date', models.DateField()),
                ('repos_affected', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('api', 'API'), ('crm', 'CRM'), ('app', 'App')], max_length=20), default=list, help_text='Which repositories this release touches', size=None)),
                ('is_major', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['-release_date'], name='wefund_rele_release_60ef2b_idx')],
            },
        ),
    ]
