# Generated by Django 5.2.3 on 2026-02-17 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0180_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in listings and meta description', max_length=500)),
                ('content', models.TextField(blank=True, help_text='HTML content from rich text editor')),
                ('featured_image', models.URLField(blank=True, help_text='BunnyCDN URL for featured/hero image', max_length=500)),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for search results (max 60 chars recommended)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Custom description for search results', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword this article targets', max_length=100)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('author_display_name', models.CharField(blank=True, help_text="Public author name (defaults to user's full name)", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reading_time_minutes', models.PositiveIntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether AI assisted in content generation')),
                ('ai_metadata', models.JSONField(blank=True, default=dict, help_text='AI generation details: model, prompts, topic research')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='wefund.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='wefund.blogtag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='wefund_blog_status_b620eb_idx'), models.Index(fields=['slug'], name='wefund_blog_slug_f8c5fe_idx')],
            },
        ),
    ]
