# Generated by Django 5.2.3 on 2026-02-20 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0181_blogcategory_blogtag_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sku_prefix', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('challenge_type', models.CharField(choices=[('1-step-algo', '1-Step Algo'), ('1-step-pro', '1-Step Pro'), ('2-step', '2-Step')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, help_text='Link to the Challenge model for enrollment creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_products', to='wefund.challenge')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Max number of uses. Null = unlimited.', null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products this code applies to. Leave blank for all products.', related_name='discount_codes', to='wefund.websiteproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('free', 'Free')], default='fixed', max_length=10)),
                ('price_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, help_text='Products this addon is available for. Leave blank for all products.', related_name='addons', to='wefund.websiteproduct')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_size', models.IntegerField(help_text='Account size in USD (e.g. 10000, 25000, 50000)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (shown as strikethrough)', max_digits=10, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('broker_type', models.CharField(choices=[('mt5', 'MetaTrader 5'), ('ctrader', 'cTrader'), ('tradelocker', 'TradeLocker')], default='mt5', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='wefund.websiteproduct')),
            ],
            options={
                'ordering': ['sort_order', 'account_size'],
                'unique_together': {('product', 'account_size', 'broker_type')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_country', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.JSONField(blank=True, default=dict)),
                ('customer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addon_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Card (Paytiko)'), ('crypto', 'Crypto (Confirmo)')], max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='External payment gateway transaction ID', max_length=255)),
                ('payment_url', models.URLField(blank=True, help_text='Payment gateway redirect URL', max_length=500)),
                ('referral_code', models.CharField(blank=True, max_length=50)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('zoho_invoice_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('zoho_contact_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoho_invoice_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoho_payment_id', models.CharField(blank=True, default='', max_length=50)),
                ('klaviyo_abandoned_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_orders', to='wefund.discountcode')),
                ('order', models.OneToOneField(blank=True, help_text='Link to the main Order record (created after payment confirmation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_order', to='wefund.order')),
                ('addons', models.ManyToManyField(blank=True, to='wefund.websiteproductaddon')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_orders', to='wefund.websiteproductvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
