# Generated by Django 5.2.3 on 2026-02-20 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wefund', '0182_websiteproduct_discountcode_websiteorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing_contacts', 'Syncing Contacts'), ('syncing_invoices', 'Syncing Invoices'), ('syncing_payments', 'Syncing Payments'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('start_invoice_number', models.PositiveIntegerField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('contacts_synced', models.PositiveIntegerField(default=0)),
                ('contacts_skipped', models.PositiveIntegerField(default=0)),
                ('contacts_failed', models.PositiveIntegerField(default=0)),
                ('invoices_synced', models.PositiveIntegerField(default=0)),
                ('invoices_skipped', models.PositiveIntegerField(default=0)),
                ('invoices_failed', models.PositiveIntegerField(default=0)),
                ('payments_synced', models.PositiveIntegerField(default=0)),
                ('payments_skipped', models.PositiveIntegerField(default=0)),
                ('payments_failed', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoho_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
