# Generated by Django 4.2 on 2026-02-20

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wefund', '0183_zohosyncjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_profile', to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('durations_offered', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Subset of [15, 30, 60] minutes', size=None)),
                ('default_duration', models.IntegerField(default=30)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('buffer_minutes', models.IntegerField(default=10)),
                ('max_days_ahead', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('google_calendar_connected', models.BooleanField(default=False)),
                ('google_access_token', models.TextField(blank=True, default='')),
                ('google_refresh_token', models.TextField(blank=True, default='')),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='wefund.meetingprofile')),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('meeting_profile', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='MeetingDateOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='wefund.meetingprofile')),
                ('date', models.DateField()),
                ('is_blocked', models.BooleanField(default=True, help_text='True=entire day blocked, False=custom hours below')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('meeting_profile', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='MeetingBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='wefund.meetingprofile')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_notes', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('timezone', models.CharField(help_text="Guest's timezone", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('daily_room_name', models.CharField(blank=True, default='', max_length=100)),
                ('daily_room_url', models.URLField(blank=True, default='')),
                ('cancel_token', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [
                    models.Index(fields=['start_time'], name='wefund_meet_start_t_idx001'),
                    models.Index(fields=['status'], name='wefund_meet_status_idx001'),
                    models.Index(fields=['meeting_profile', 'start_time'], name='wefund_meet_meeting_idx001'),
                ],
            },
        ),
    ]
